use crate::models::common::*;
use crate::models::serde::NewLineDelimited;

pub type TagList = NewLineDelimited;

#[derive(Debug, Clone, Deserialize)]
pub struct UserProfile {
    pub last_logged_in_at: Timestamp,
    pub id: UserId,
    pub name: String,
    pub level: u64,
    pub inviter_id: Option<UserId>,
    pub created_at: Timestamp,
    pub last_forum_read_at: Timestamp,
    pub comment_threshold: i64,
    pub updated_at: Timestamp,
    pub default_image_size: String,
    pub favorite_tags: TagList,
    pub blacklisted_tags: TagList,
    pub time_zone: String,
    pub post_update_count: u64,
    pub note_update_count: u64,
    pub favorite_count: u64,
    pub post_upload_count: u64,
    pub per_page: u64,
    pub theme: String,
    pub is_banned: bool,
    pub can_approve_posts: bool,
    pub can_upload_free: bool,
    pub level_string: String,
    pub has_mail: bool,
    pub receive_email_notifications: bool,
    pub always_resize_images: bool,
    pub enable_post_navigation: bool,
    pub new_post_navigation_layout: bool,
    pub enable_private_favorites: bool,
    pub enable_sequential_post_navigation: bool,
    pub hide_deleted_posts: bool,
    pub style_usernames: bool,
    pub enable_auto_complete: bool,
    pub show_deleted_children: bool,
    pub has_saved_searches: bool,
    pub disable_categorized_saved_searches: bool,
    pub is_super_voter: bool,
    pub disable_tagged_filenames: bool,
    pub enable_recent_searches: bool,
    pub disable_cropped_thumbnails: bool,
    pub disable_mobile_gestures: bool,
    pub enable_safe_mode: bool,
    pub enable_desktop_mode: bool,
    pub disable_post_tooltips: bool,
    pub enable_recommended_posts: bool,
    pub opt_out_tracking: bool,
    pub no_flagging: bool,
    pub no_feedback: bool,
    pub requires_verification: bool,
    pub is_verified: bool,
    pub api_regen_multiplier: u64,
    pub api_burst_limit: u64,
    pub remaining_api_limit: f64,
    pub statement_timeout: u64,
    pub favorite_group_limit: u64,
    pub favorite_limit: u64,
    pub tag_query_limit: u64,
    pub max_saved_searches: u64,
    pub wiki_page_version_count: u64,
    pub artist_version_count: u64,
    pub artist_commentary_version_count: u64,
    pub pool_version_count: Option<u64>,
    pub forum_post_count: u64,
    pub comment_count: u64,
    pub favorite_group_count: u64,
    pub appeal_count: u64,
    pub flag_count: u64,
    pub positive_feedback_count: u64,
    pub neutral_feedback_count: u64,
    pub negative_feedback_count: u64,
}
